[workspace]
members = [
    "my-macros"
]

[package]
name = "rust-learn"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.36", features = ["full"] }
my-macros = { path = "./my-macros" }
